<?php

namespace Nantarena\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryTypeRepository extends EntityRepository
{
}
