<?php

namespace Nantarena\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Nantarena\EventBundle\Entity\Event;
use Nantarena\UserBundle\Entity\User;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    public function findByEvent(Event $event)
    {
        return $this->createQueryBuilder('e')
            ->join('e.entryType', 'et')
            ->addSelect('et')
            ->where('et.event = :event')
            ->setParameter('event', $event)
            ->getQuery()
            ->getResult();
    }

    public function findByEventAndUser(Event $event, User $user)
    {
        return $this->createQueryBuilder('e')
            ->join('e.entryType', 'et')
            ->addSelect('et')
            ->where('et.event = :event')
            ->andWhere('e.user = :user')
            ->setParameter('event', $event)
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
