<?php

namespace Nantarena\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Nantarena\EventBundle\Entity\Event;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    public function findByEvent(Event $event)
    {
        return $this->createQueryBuilder('e')
            ->join('e.entryType', 'et')
            ->addSelect('et')
            ->where('et.event = :event')
            ->setParameter('event', $event)
            ->getQuery()
            ->getResult();
    }
}
