<?php

namespace Nantarena\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findWithAll($id)
    {
        return $this->createQueryBuilder('e')
            ->join('e.entryTypes', 'et')
            ->addSelect('et')
            ->join('et.entryType', 't')
            ->addSelect('t')
            ->join('e.tournaments', 'to')
            ->addSelect('to')
            ->join('to.game', 'g')
            ->addSelect('g')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }
}
