<?php

namespace Nantarena\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findWithAll($id)
    {
        return $this->createQueryBuilder('e')
            ->join('e.entryTypes', 'et')
            ->addSelect('et')
            ->leftJoin('e.tournaments', 'to')
            ->addSelect('to')
            ->leftJoin('to.game', 'g')
            ->addSelect('g')
            ->leftJoin('to.admin', 'u')
            ->addSelect('u')
            ->leftJoin('e.rules', 'r1')
            ->addSelect('r1')
            ->leftJoin('e.autorization', 'r2')
            ->addSelect('r2')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }

    public function findOneShow($slug)
    {
        return $this->createQueryBuilder('e')
            ->join('e.entryTypes', 'et')
            ->addSelect('et')
            ->leftJoin('e.tournaments', 'to')
            ->addSelect('to')
            ->leftJoin('to.game', 'g')
            ->addSelect('g')
            ->leftJoin('to.admin', 'u')
            ->addSelect('u')
            ->where('e.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getSingleResult();
    }

    public function findNext()
    {
        return $this->createQueryBuilder('e')
            ->orderBy('e.startDate', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
