parameters:

services:
    nantarena_forum.admin_event:
        class: Nantarena\ForumBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard }

    nantarena_forum.read_status_subscriber:
        class: Nantarena\ForumBundle\EventListener\ReadStatusSubscriber
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber }

    nantarena_forum.acl_subscriber:
        class: Nantarena\ForumBundle\EventListener\AclSubscriber
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setContainer, [@service_container] ]

    # Managers
    nantarena_forum.category_manager:
        class: Nantarena\ForumBundle\Manager\CategoryManager
        arguments: [@router]

    nantarena_forum.forum_manager:
        class: Nantarena\ForumBundle\Manager\ForumManager
        arguments: [@router]

    nantarena_forum.thread_manager:
        class: Nantarena\ForumBundle\Manager\ThreadManager
        arguments: [@router]

    nantarena_forum.post_manager:
        class: Nantarena\ForumBundle\Manager\PostManager
        arguments: [@router]

    nantarena_forum.acl_manager:
        class: Nantarena\ForumBundle\Security\Acl\AclManager
        arguments: [@security.acl.provider, @security.context]

    # Extensions twig
    nantarena_forum.twig.category_extension:
        class: Nantarena\ForumBundle\Twig\CategoryExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [@service_container] ]

    nantarena_forum.twig.forum_extension:
        class: Nantarena\ForumBundle\Twig\ForumExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [@service_container] ]

    nantarena_forum.twig.thread_extension:
        class: Nantarena\ForumBundle\Twig\ThreadExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [@service_container] ]

    nantarena_forum.twig.post_extension:
        class: Nantarena\ForumBundle\Twig\PostExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [@service_container] ]

    nantarena_forum.twig.bbcode_extension:
        class: Nantarena\ForumBundle\Twig\BbcodeExtension
        tags:
            - { name: twig.extension }

    # Validateurs
    nantarena_forum.sticky_validator:
        class: Nantarena\ForumBundle\Validator\Constraints\StickyValidator
        arguments: [@security.context]
        tags:
            - { name: validator.constraint_validator, alias: sticky_validator }
